### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by pksunkara**

### CODE REVIEW

**Comment by Baggz** [comment]
@pksunkara 

IMHO it would be good to mention what are the alternatives.

**Comment by pksunkara** [comment]
@Baggz There is no alternative. The functionality has been absorbed by swagger adapter but that is only for swagger. As a general use of this library, we won't be supporting it.

**Comment by kylef** [comment]
I think there is an alternative, the alternative is that you can use json-schema-faker directly.

**Comment by pksunkara** [comment]
But json-schema-faker won't contain the logic for injecting the message bodies into refract.

**Pull request merged**
